# Grant jpi write access to laptop power-tuning sysfs interfaces
z /sys/class/drm/card*-eDP-1/amdgpu/panel_power_savings 0664 root jpi - -
z /sys/module/snd_hda_intel/parameters/power_save 0664 root jpi - -
